#!/bin/bash
# =============================================================================
# NyayAI / LibreChat - Import Users into MongoDB
# Usage: ./import_users.sh --file <path-to-export.json> [OPTIONS]
#
# Options:
#   --file        Path to the JSON file produced by export_users.sh (required)
#   --container   Docker container name (default: chat-mongodb)
#   --db          MongoDB database name (default: LibreChat)
#   --mongo-uri   Full MongoDB URI (overrides --container/--db)
#   --mode        Import mode:
#                   skip   (default) - skip users that already exist by email
#                   upsert           - update existing users if email matches
#                   insert-only      - fail the whole import if any duplicate found
#   --dry-run     Preview what would be imported without writing anything
#   --default-role  Role to assign if user document has no role field (default: USER)
#
# IMPORTANT NOTES:
#   1. Passwords: LibreChat stores bcrypt hashes. If the export did NOT include
#      sensitive fields (default), imported users will have NO password and must
#      use "Forgot Password" to set one, OR you can invite them via the app.
#   2. If the export DID include password hashes (--include-sensitive), they are
#      portable only if both instances use the same bcrypt cost/salt rounds.
#   3. ObjectId fields (_id) are preserved on import so conversation history
#      links remain intact when migrating between identical instances.
#   4. Always take a MongoDB backup before running imports in production.
# =============================================================================

set -euo pipefail

# ---- Defaults ---------------------------------------------------------------
CONTAINER="chat-mongodb"
DB="LibreChat"
MONGO_URI=""
INPUT_FILE=""
MODE="skip"
DRY_RUN=false
DEFAULT_ROLE="USER"

# ---- Argument parsing -------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --file)         INPUT_FILE="$2";    shift 2 ;;
    --container)    CONTAINER="$2";     shift 2 ;;
    --db)           DB="$2";            shift 2 ;;
    --mongo-uri)    MONGO_URI="$2";     shift 2 ;;
    --mode)         MODE="$2";          shift 2 ;;
    --dry-run)      DRY_RUN=true;       shift 1 ;;
    --default-role) DEFAULT_ROLE="$2";  shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ---- Validate ---------------------------------------------------------------
if [[ -z "$INPUT_FILE" ]]; then
  echo "❌  ERROR: --file is required."
  echo "    Usage: ./import_users.sh --file librechat_users_20250312.json"
  exit 1
fi

if [[ ! -f "$INPUT_FILE" ]]; then
  echo "❌  ERROR: File not found: ${INPUT_FILE}"
  exit 1
fi

if [[ "$MODE" != "skip" && "$MODE" != "upsert" && "$MODE" != "insert-only" ]]; then
  echo "❌  ERROR: --mode must be one of: skip | upsert | insert-only"
  exit 1
fi

# ---- Read and validate the JSON file ----------------------------------------
echo "📂 Reading export file: ${INPUT_FILE}"
USER_JSON=$(cat "${INPUT_FILE}")

# Quick sanity check: ensure it looks like our export format
if ! echo "${USER_JSON}" | grep -q '"users"'; then
  echo "❌  ERROR: File does not appear to be a LibreChat user export (missing 'users' key)."
  echo "    Make sure you're using a file generated by export_users.sh."
  exit 1
fi

TOTAL_IN_FILE=$(echo "${USER_JSON}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
print(len(data.get('users', [])))
" 2>/dev/null || echo "unknown")

echo "   Users in file : ${TOTAL_IN_FILE}"
echo "   Mode          : ${MODE}"
echo "   Dry run       : ${DRY_RUN}"
echo ""

if [[ "$DRY_RUN" == "true" ]]; then
  echo "🔍 DRY RUN — listing users that WOULD be imported:"
  echo "${USER_JSON}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
users = data.get('users', [])
print(f'{'No.':<5} {'Name':<25} {'Email':<35} {'Role':<10} {'Provider':<12}')
print('-' * 90)
for i, u in enumerate(users, 1):
    print(f\"{i:<5} {u.get('name','')[:23]:<25} {u.get('email','')[:33]:<35} {u.get('role','USER'):<10} {u.get('provider','local'):<12}\")
print()
print(f'Total: {len(users)} user(s) would be imported (mode: ${MODE})')
"
  exit 0
fi

# ---- Build the mongosh import script ----------------------------------------
# We embed the users JSON inline into the mongosh script.
# This avoids needing mongoimport or copying files into the container.

MONGO_SCRIPT=$(python3 -c "
import sys, json

with open('${INPUT_FILE}') as f:
    data = json.load(f)

users = data.get('users', [])
mode = '${MODE}'
default_role = '${DEFAULT_ROLE}'
db_name = '${DB}'

# Build JS array of user objects, safely escaped
users_js = json.dumps(users)

script = f'''
db = db.getSiblingDB('{db_name}');

var importedUsers = {users_js};
var mode = '{mode}';
var defaultRole = '{default_role}';
var stats = {{ inserted: 0, updated: 0, skipped: 0, errors: 0 }};

importedUsers.forEach(function(u) {{
  try {{
    // Ensure required fields
    if (!u.email) {{ print('SKIP (no email): ' + JSON.stringify(u._id)); stats.errors++; return; }}
    if (!u.role) u.role = defaultRole;
    if (!u.provider) u.provider = 'local';
    if (u.createdAt && typeof u.createdAt === 'string') u.createdAt = new Date(u.createdAt);
    if (u.updatedAt && typeof u.updatedAt === 'string') u.updatedAt = new Date(u.updatedAt);

    var existing = db.users.findOne({{ email: u.email }});

    if (mode === 'insert-only') {{
      if (existing) {{
        print('ERROR (duplicate): ' + u.email);
        stats.errors++;
        return;
      }}
      db.users.insertOne(u);
      print('INSERTED: ' + u.email);
      stats.inserted++;

    }} else if (mode === 'upsert') {{
      var result = db.users.updateOne(
        {{ email: u.email }},
        {{ \$set: u }},
        {{ upsert: true }}
      );
      if (result.upsertedCount > 0) {{
        print('INSERTED (upsert): ' + u.email);
        stats.inserted++;
      }} else {{
        print('UPDATED: ' + u.email);
        stats.updated++;
      }}

    }} else {{
      // Default: skip
      if (existing) {{
        print('SKIPPED (exists): ' + u.email);
        stats.skipped++;
        return;
      }}
      db.users.insertOne(u);
      print('INSERTED: ' + u.email);
      stats.inserted++;
    }}
  }} catch(e) {{
    print('ERROR on ' + u.email + ': ' + e.message);
    stats.errors++;
  }}
}});

print('');
print('========== Import Summary ==========');
print('Inserted : ' + stats.inserted);
print('Updated  : ' + stats.updated);
print('Skipped  : ' + stats.skipped);
print('Errors   : ' + stats.errors);
print('====================================');
''';

print(script)
")

# ---- Execute ----------------------------------------------------------------
echo "🚀 Starting import into container '${CONTAINER}' → DB '${DB}'..."
echo ""
docker exec -i "${CONTAINER}" mongosh --quiet --eval "${MONGO_SCRIPT}"
echo ""
echo "✅ Import complete. Review the summary above."
echo ""
echo "⚠️  REMINDER: If users were imported without password hashes, they must"
echo "   use the 'Forgot Password' flow to set a new password before logging in."
